spring.application.name: forex-service
server.port: 8010
eureka.client.service-url.default-zone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      clientId: ivan
      clientSecret: ivan-secret
    resource:
      tokenInfoUri: http://localhost:8070/oauth/check_token

logging.level.root: DEBUG