spring.application.name: forex-service
server.port: 8010
eureka.client.service-url.default-zone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      clientId: ivan
      clientSecret: ivan-secret
    resource:
      jwt.key-value: 123

logging.level.root: DEBUG