spring.application.name: currency-conversion-service
server.port: 8001
eureka.client.service-url.default-zone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: ivan
      clientSecret: ivan-secret
    resource:
      jwt.key-value: 123