spring.application.name: zuul
server.port: 8762
eurika:
  instance.preferIfAddress: true
  serviceurl.defaultzone: http://localhost:8761/eurika/
  client:
    registerWithEurika: true
    fetchRegistry: true
zuul:
#  prefix: /api - common prefix for all api
  routes:
    forex:
      path: /forex/**
      serviceId: forex-service
    currency:
      path: /currency/**
      serviceId: currency-conversion-service
