spring:
  application:
    name: zuul
server:
  port: 8762

eureka:
  instance:
    preferIfAddress: true
  serviceUrl:
    defaultzone: http://localhost:8761/eurika/
  client:
    registerWithEurika: true
    fetchRegistry: true

zuul:
#  prefix: /api - common prefix for all requests
  routes:
    forex:
      path: /forex/**
      serviceId: forex-service
    currency:
      path: /currency/**
      serviceId: currency-conversion-service
  sensitiveHeaders: Cookie,Set-Cookie

management:
  endpoints:
    web:
      exposure:
        include: '*'
